name: Publish v0.3.0

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/publish-v0.3.0.yml'

permissions:
  contents: read
  packages: write

jobs:
  release:
    uses: ./.github/workflows/release.yml
    with:
      release_tag: v0.3.0
    secrets: inherit
